repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents,--unsafe]
    -   id: detect-aws-credentials
    -   id: trailing-whitespace
