AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ApplicationName:
    Type: String
  WebsiteURL:
    Type: String
  Referer:
    Type: String
  CertArn:
    Type: String

Resources:
  CFDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Sub "${WebsiteURL}.s3-website.${AWS::Region}.amazonaws.com"
          Id: !Sub "S3-${WebsiteURL}"
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
          OriginCustomHeaders:
            - HeaderName: Referer
              HeaderValue: !Ref Referer
        HttpVersion: http2
        Enabled: 'true'
        DefaultRootObject: index.html
        Aliases:
          - !Sub "www.${WebsiteURL}"  #requires certificate
          - !Ref WebsiteURL
        DefaultCacheBehavior:
          TargetOriginId: !Sub "S3-${WebsiteURL}"
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          SmoothStreaming: 'false'
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 #caching-optimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf #cors-s3origin https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1.2_2021
          AcmCertificateArn: !Ref CertArn
          SslSupportMethod: sni-only
      Tags:
        - Key: stack
          Value: !Ref ApplicationName

Outputs:
  CloudFrontDomainName:
    Description: The generated DNS name for the cloudfront Distribution
    Value: !GetAtt CFDistribution.DomainName